# Generated by Django 4.1.5 on 2023-01-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="coa",
            fields=[
                (
                    "코드",
                    models.CharField(
                        default="", max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("계정명", models.CharField(blank=True, default="", max_length=20)),
                ("계정_대분류", models.CharField(blank=True, default="", max_length=20)),
                ("계정_중분류", models.CharField(blank=True, default="", max_length=20)),
                ("계정_소분류", models.CharField(blank=True, default="", max_length=20)),
                ("재무제표", models.CharField(blank=True, default="", max_length=20)),
                ("비고", models.CharField(blank=True, default="", max_length=100)),
            ],
            options={
                "db_table": "api_coa",
                "ordering": ["코드"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "제품코드",
                    models.CharField(
                        default="", max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("제품명", models.CharField(blank=True, default="", max_length=20)),
                ("포장단위", models.CharField(blank=True, default="", max_length=20)),
                ("제약사", models.CharField(blank=True, default="", max_length=20)),
                ("보험코드", models.CharField(blank=True, default="", max_length=20)),
                ("표준코드", models.CharField(blank=True, default="", max_length=20)),
                ("기준가", models.CharField(blank=True, default="", max_length=20)),
                ("급여", models.CharField(blank=True, default="", max_length=20)),
                ("구분", models.CharField(blank=True, default="", max_length=20)),
                ("성분코드", models.CharField(blank=True, default="", max_length=20)),
            ],
            options={
                "db_table": "api_product",
                "ordering": ["제품코드"],
                "managed": True,
            },
        ),
    ]
