# Generated by Django 4.1.5 on 2023-01-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_coa_계정_대분류_alter_coa_계정_소분류_alter_coa_계정_중분류_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coa",
            name="코드",
            field=models.IntegerField(default="", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="제품코드",
            field=models.IntegerField(default="", primary_key=True, serialize=False),
        ),
    ]
