# Generated by Django 4.1.7 on 2023-02-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='직위',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='hr',
            name='직책',
            field=models.CharField(default='', max_length=10),
        ),
    ]
