# Generated by Django 4.1.7 on 2023-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_hr_직위_alter_hr_직책'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='경력사항5',
            new_name='경력사항10',
        ),
        migrations.RenameField(
            model_name='hr',
            old_name='어학사항5',
            new_name='어학사항10',
        ),
        migrations.RenameField(
            model_name='hr',
            old_name='자격사항5',
            new_name='자격사항10',
        ),
        migrations.AlterField(
            model_name='hr',
            name='개인이메일',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hr',
            name='구분',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='hr',
            name='근무지',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='hr',
            name='부서',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='hr',
            name='이름',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='hr',
            name='회사이메일',
            field=models.CharField(default='', max_length=100),
        ),
    ]
