# Generated by Django 4.1.7 on 2023-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_경력사항5_hr_경력사항10_rename_어학사항5_hr_어학사항10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='직책',
            field=models.CharField(default='', max_length=30),
        ),
    ]
