# Generated by Django 4.1.7 on 2023-02-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_hr_직책'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='직위',
            new_name='직급',
        ),
        migrations.RenameField(
            model_name='hr',
            old_name='최종학위',
            new_name='학위',
        ),
    ]
