# Generated by Django 4.1.7 on 2023-02-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_직위_hr_직급_rename_최종학위_hr_학위'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='경력사항10',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='어학사항10',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='자격사항10',
        ),
        migrations.AddField(
            model_name='hr',
            name='경력사항5',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='어학사항5',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='자격사항5',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='개인이메일',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='경력사항1',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='경력사항2',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='경력사항3',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='경력사항4',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='구분',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='근무지',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='근속일',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='부서',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='비상연락망',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='어학사항1',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='어학사항2',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='어학사항3',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='어학사항4',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='연락처',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='영문이름',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='이름',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='입사구분',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='자격사항1',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='자격사항2',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='자격사항3',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='자격사항4',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='전공',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='주민등록번호',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='주소',
            field=models.CharField(default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='직급',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='직책',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='최종학력',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='팀',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='학교',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='학위',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='학점',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='회사이메일',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
