# Generated by Django 4.1.7 on 2023-02-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_hr_경력사항10_remove_hr_어학사항10_remove_hr_자격사항10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='구분',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='근무지',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='부서',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='이름',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='입사구분',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='직급',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='최종학력',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='학위',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='학점',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
