# Generated by Django 4.1.7 on 2023-02-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_hr_구분_alter_hr_근무지_alter_hr_부서_alter_hr_이름_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='생년월일',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='입사일',
            field=models.DateField(null=True),
        ),
    ]
