# Generated by Django 4.1.7 on 2023-02-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_hr_생년월일_alter_hr_입사일'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hr',
            options={'managed': True, 'ordering': ['사번']},
        ),
        migrations.AlterModelTable(
            name='hr',
            table='api_hr',
        ),
    ]
