# Generated by Django 4.1.7 on 2023-02-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_hr_options_alter_hr_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='사번',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
