# Generated by Django 4.1.7 on 2023-02-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_hr_사번'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
