# Generated by Django 4.1.7 on 2023-03-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_hr_개인이메일_alter_hr_경력사항1_alter_hr_경력사항2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hr",
            name="is_activate",
        ),
    ]
