# Generated by Django 4.1.7 on 2023-03-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_remove_hr_is_activate"),
    ]

    operations = [
        migrations.AddField(
            model_name="hr",
            name="is_activate",
            field=models.BooleanField(default=True),
        ),
    ]
