# Generated by Django 4.1.7 on 2023-03-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_remove_hr_is_activate_hr_재직or퇴직"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr",
            name="재직or퇴직",
            field=models.CharField(blank=True, default="재직", max_length=2, null=True),
        ),
    ]
